### ISSUE TITLE
Pick a clear license for the project

### ISSUE THREAD

**Issue by ncoghlan** [ncoghlan/python-userref#1]
@csabella While this was just an archive repo for the old draft manuscript, the exact licensing didn't matter all that much. That situation has changed now that you're actively working on the reStructured Text conversion.

While I use CC0 for my personal blog, that doesn't feel like the right choice for a shared project.

The Python Packaging User Guide is under CC-BY-SA: https://github.com/pypa/python-packaging-user-guide#license

And I don't think this is a project where we want to encourage private derivatives, so the reduced redistribution obligations of CC-BY don't seem desirable.

So if you're also happy with CC-BY-SA, I'll amend the README to be explicit about that.

**Comment by csabella** [comment]
Thank you for asking.  CC-BY-SA looks like a good option unless you wanted to limit commercial options ([CC-BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/)).

**Comment by ncoghlan** [comment]
I find the Non-Commercial variants of the CC licenses overly murky from a legal perspective, so if that were to ever become a concern, I'd look at something along the lines of the Creator Endorsed marks from Question Copyright: https://questioncopyright.org/creator_endorsed_mark

So CC-BY-SA it is :)
